version: '3'

services:
  backend:
    build:
      context: ./server
    ports:
      - "8000:8000"
    volumes:
      - servervol:/serverdata

  frontend:
    build:
      context: ./client
    depends_on:
      - backend
    volumes:
      - clientvol:/clientdata

volumes:
  servervol:
  clientvol: